### ISSUE TITLE
调用父类方法传递不了参数

### ISSUE THREAD

**Issue by torns** [yviscool/egg-pig#2]
0.3.0版本,控制器子类调用父类方法时,传递不了参数

**Comment by yviscool** [comment]
@torns 我自己测试是可以传的， 给个代码我看看。

**Comment by torns** [comment]
//Index控制器
import { Controller, Get, Query, ParseIntPipe } from 'egg-pig';
import BaseController from './base';
@Controller('index')
export default class IndexController extends BaseController {
  @Get('index')
  public async index(@Query('id', ParseIntPipe) id) {
    return await this.sendSucRest({ id: id })
  }
}

//基础控制器
import { Context, BaseContextClass } from 'egg';
import { Controller } from 'egg-pig';
@Controller('base')
export default class BaseController extends BaseContextClass {
  public async sendSucRest(data: any = {}, msg: string = "成功") {
    await this.ctx.body = { restData: data, statusCode: 1, msg: msg };
  }
}

**Comment by torns** [comment]
找到原因了,发现基类不能加@controller('base'), 不加又routes_resolver.js中的const { name = '', prefix, isRestful } = routerMetadata;报错 routerMetadata为null

**Comment by torns** [comment]
@yviscool 
找到原因了,发现基类不能加@controller('base'), 不加又routes_resolver.js中的const { name = '', prefix, isRestful } = routerMetadata;报错 routerMetadata为null

**Comment by yviscool** [comment]
@torns 
基础控制器放在 app/controller 目录下？，如果是这样，那么会代理其方法，所以参数用不了，要是去掉 Controller 装饰器会报错(晚上看看)。暂时建议基础控制器放到 app/core 下面，不添加 Controller 装饰器，这样就可以。另外继承的话，path 是不会追加的，这个获取比较麻烦。
