### ISSUE TITLE
控制器调用父类abstract方法会直接返回输出

### ISSUE THREAD

**Issue by torns** [yviscool/egg-pig#3]
/**
 * 基础控制器
 */
import { Controller } from "egg";
export default abstract class BaseIndexController extends Controller {
  public abstract getMyName():string;
}

/**
 * 首页控制器
 */
import { Controller, Get } from 'egg-pig';
import BaseIndexController from './baseIndex';
@Controller('/admin')
export default class IndexController extends BaseIndexController {
  public getMyName(): string {
    return 'China';
  }
  @Get('/test')
  public async test() {
    let name = this.getMyName();
    this.ctx.body={ name:name }
  }
}

调用/admin/test本应该输出{ name:"China" },现在却直接输出China

**Comment by yviscool** [comment]
我看看，

**Comment by yviscool** [comment]
@torns  还是被代理的事情，调用被代理过的 getMyName 直接处理了，等我假寐一下，休休
