### ISSUE TITLE
pipe会重复执行

### ISSUE THREAD

**Issue by BySlin** [yviscool/egg-pig#4]
` 
import { BaseContextClass } from 'egg';
import { Controller, Get, ParseIntPipe, Query, } from 'egg-pig';

@Controller('user')
export default class UserController extends BaseContextClass {

    @Get('id')
    async findById(@Query('id', ParseIntPipe) id: number) {
        return id;
    }

}
`
第一次调用会成功
后面调用会返回
`{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Validation failed (numeric string is expected)"
}`
`
route_proxy.js  
每次请求控制器会重复添加pipes,导致pipe重复执行
pipes = pipes.concat(paramPipes).map(pipe => Object.assign(pipe, this));

第一次请求pipes.length 为 1,控制器成功返回
第二次请求pipes.length 为 2,pipes包含两个ParseIntPipe 第一次执行 id 为 string ‘1’ 转换为 int 1
第二个ParseIntPipe 执行 1 已经为int 返回 BadRequestException
后面多次请求，pipes中就会有多少ParseIntPipe

ValidationPipe，ParseIntPipe，自定义Pipe均存在此问题

`

**Comment by yviscool** [comment]
@BySlin  我看看

**Comment by yviscool** [comment]
@BySlin 已修复
