### ISSUE TITLE
使用ValidatePipe问题：@Body(new ValidationPipe({ transform: true })) body报错，见下面

### ISSUE THREAD

**Issue by lmoyrd** [yviscool/egg-pig#5]
public async delete(@Body(new ValidationPipe({ transform: true })) body: DeleteDTO) {}
会报下面的错误。
at EventEmitter.emit (events.js:317:22)
    at ChildProcess.<anonymous> (internal/cluster/master.js:192:13)
    at Object.onceWrapper (events.js:412:26)
    at ChildProcess.emit (events.js:305:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
name: "AppWorkerDiedError"
pid: 14714

[cfork:master:14714] worker:14721 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: false)
[cfork:master:14714] don't fork new work (refork: false)
INFO 14714 [master] app_worker#1:14721 disconnect, suicide: true, state: disconnected, current workers: []
[cfork:master:14714] worker:14721 exit (code: 0, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)

我把断点打到validate.pipe.js里，调用不到，看不到具体的错误信息。
去掉new ValidationPipe({ transform: true })这句话，delete能正常在被请求到。
@yviscool

**Comment by lmoyrd** [comment]
升级了egg版本也没用==

**Comment by lmoyrd** [comment]
需要安装class-transformer

**Comment by yviscool** [comment]
@lmoyrd 不会报缺少这两个包的错误信息？
